/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /nfs/home/tsweet/workspace/DHS/src/dhs/msg/person.msg
 *
 */


#ifndef DHS_MESSAGE_PERSON_H
#define DHS_MESSAGE_PERSON_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dhs
{
template <class ContainerAllocator>
struct person_
{
  typedef person_<ContainerAllocator> Type;

  person_()
    : upper_red(0)
    , upper_green(0)
    , upper_blue(0)
    , lower_red(0)
    , lower_green(0)
    , lower_blue(0)  {
    }
  person_(const ContainerAllocator& _alloc)
    : upper_red(0)
    , upper_green(0)
    , upper_blue(0)
    , lower_red(0)
    , lower_green(0)
    , lower_blue(0)  {
    }



   typedef uint8_t _upper_red_type;
  _upper_red_type upper_red;

   typedef uint8_t _upper_green_type;
  _upper_green_type upper_green;

   typedef uint8_t _upper_blue_type;
  _upper_blue_type upper_blue;

   typedef uint8_t _lower_red_type;
  _lower_red_type lower_red;

   typedef uint8_t _lower_green_type;
  _lower_green_type lower_green;

   typedef uint8_t _lower_blue_type;
  _lower_blue_type lower_blue;




  typedef boost::shared_ptr< ::dhs::person_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dhs::person_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct person_

typedef ::dhs::person_<std::allocator<void> > person;

typedef boost::shared_ptr< ::dhs::person > personPtr;
typedef boost::shared_ptr< ::dhs::person const> personConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dhs::person_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dhs::person_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dhs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'dhs': ['/nfs/home/tsweet/workspace/DHS/src/dhs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dhs::person_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dhs::person_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dhs::person_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dhs::person_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dhs::person_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dhs::person_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dhs::person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b1c29f70675460405e64a004cc34ba02";
  }

  static const char* value(const ::dhs::person_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb1c29f7067546040ULL;
  static const uint64_t static_value2 = 0x5e64a004cc34ba02ULL;
};

template<class ContainerAllocator>
struct DataType< ::dhs::person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dhs/person";
  }

  static const char* value(const ::dhs::person_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dhs::person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 upper_red\n\
uint8 upper_green\n\
uint8 upper_blue\n\
uint8 lower_red\n\
uint8 lower_green\n\
uint8 lower_blue\n\
\n\
\n\
";
  }

  static const char* value(const ::dhs::person_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dhs::person_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.upper_red);
      stream.next(m.upper_green);
      stream.next(m.upper_blue);
      stream.next(m.lower_red);
      stream.next(m.lower_green);
      stream.next(m.lower_blue);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct person_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dhs::person_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dhs::person_<ContainerAllocator>& v)
  {
    s << indent << "upper_red: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.upper_red);
    s << indent << "upper_green: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.upper_green);
    s << indent << "upper_blue: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.upper_blue);
    s << indent << "lower_red: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.lower_red);
    s << indent << "lower_green: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.lower_green);
    s << indent << "lower_blue: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.lower_blue);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DHS_MESSAGE_PERSON_H
